/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tmg.assignment;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author mitch
 */
public class EmployeeAndCustomerManagementForm extends javax.swing.JFrame {
    
    ArrayList<Customer> customers = new ArrayList<Customer>();
    ArrayList<Employee> employees = new ArrayList<Employee>();


    /**
     * Creates new form EmployeeAndCustomerManagementForm
     */
    public EmployeeAndCustomerManagementForm() {
        initComponents();
        isCustomerVisible(false);
        isEmployeeVisible(false);
        isEmployeeSaveVisible(false);
        isCustomerSaveVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        empSearchButton = new javax.swing.JButton();
        searchEmpIDTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        empNameTextField = new javax.swing.JLabel();
        resultsEmpNameTextField = new javax.swing.JTextField();
        resultsEmpDOBTextField = new javax.swing.JTextField();
        empDOBTextField = new javax.swing.JLabel();
        empAddressTextField = new javax.swing.JLabel();
        resultsEmpAddressTextField = new javax.swing.JTextField();
        resultsEmpPhoneTextField = new javax.swing.JTextField();
        empPhoneTextField = new javax.swing.JLabel();
        empPhoneExtensionTextField = new javax.swing.JLabel();
        resultsEmpPhoneExtensionTextField = new javax.swing.JTextField();
        resultsEmpUsernameTextField = new javax.swing.JTextField();
        empUsernameTextField = new javax.swing.JLabel();
        empGenderTextField = new javax.swing.JLabel();
        resultsEmpGenderComboBox = new javax.swing.JComboBox<>();
        empSearchResultsTextField = new javax.swing.JLabel();
        updateEmployeeButton = new javax.swing.JButton();
        saveEmployeeUpdateButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cuNameTextField = new javax.swing.JLabel();
        resultsCuNameTextField = new javax.swing.JTextField();
        cuDOBTextField = new javax.swing.JLabel();
        resultsCuDOBTextField = new javax.swing.JTextField();
        cuAddressTextField = new javax.swing.JLabel();
        resultsCuAddressTextField = new javax.swing.JTextField();
        cuPhoneTextField = new javax.swing.JLabel();
        resultsCuPhoneTextField = new javax.swing.JTextField();
        cuLicenseNumberTextField = new javax.swing.JLabel();
        resultsCuLicenseNumberTextField = new javax.swing.JTextField();
        cuLicenseExpiryTextField = new javax.swing.JLabel();
        cuAgeTextField = new javax.swing.JLabel();
        resultsCuGenderComboBox = new javax.swing.JComboBox<>();
        resultsCuLicenseExpiryTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        SearchCuIDTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        searchCuIDButton = new javax.swing.JButton();
        cuSearchResultsTextField = new javax.swing.JLabel();
        resultsCuAgeTextField = new javax.swing.JTextField();
        cuGenderTextField = new javax.swing.JLabel();
        updateCustomerButton = new javax.swing.JButton();
        saveCustomerUpdateButton = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        addEmIDTextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        addEmNameTextField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        addEmAddressTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        addEmPhoneTextField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        addEmPhoneExtensionTextField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        addEmUsernameTextField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        addEmGenderComboBox = new javax.swing.JComboBox<>();
        addEmDOBDatePicker = new org.jdesktop.swingx.JXDatePicker();
        addNewEmButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        addCuIDTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        addCuNameTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        addCuAddressTextField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        addCuPhoneTextField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        addCuLicenseNumberTextField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        addCuGenderComboBox = new javax.swing.JComboBox<>();
        addCuDOBDatePicker = new org.jdesktop.swingx.JXDatePicker();
        addCuLicenseExpiryDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel44 = new javax.swing.JLabel();
        addCuAgeTextField = new javax.swing.JTextField();
        addNewCuButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        inputStartRentalDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputEndRentalDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        rentalDisplayTable = new javax.swing.JTable();
        searchRentalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setText("Employee and Customer Management");

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Search/Update Employee");

        empSearchButton.setText("Search");
        empSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSearchButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Search by ID:");

        empNameTextField.setText("Name:");

        empDOBTextField.setText("Date of Birth:");

        empAddressTextField.setText("Address:");

        empPhoneTextField.setText("Phone Number:");

        empPhoneExtensionTextField.setText("Phone Extension:");

        empUsernameTextField.setText("Username:");

        empGenderTextField.setText("Gender:");

        resultsEmpGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        empSearchResultsTextField.setForeground(new java.awt.Color(255, 0, 51));
        empSearchResultsTextField.setText("Search Results");

        updateEmployeeButton.setText("Update");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });

        saveEmployeeUpdateButton.setText("Save");
        saveEmployeeUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEmployeeUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(searchEmpIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empSearchButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(updateEmployeeButton)
                        .addGap(68, 68, 68)
                        .addComponent(saveEmployeeUpdateButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empDOBTextField)
                                    .addComponent(empPhoneTextField)
                                    .addComponent(empPhoneExtensionTextField)
                                    .addComponent(empUsernameTextField)
                                    .addComponent(empGenderTextField)
                                    .addComponent(empNameTextField)
                                    .addComponent(empAddressTextField))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(resultsEmpDOBTextField)
                                    .addComponent(resultsEmpNameTextField)
                                    .addComponent(resultsEmpAddressTextField)
                                    .addComponent(resultsEmpPhoneTextField)
                                    .addComponent(resultsEmpPhoneExtensionTextField)
                                    .addComponent(resultsEmpUsernameTextField)
                                    .addComponent(resultsEmpGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(empSearchResultsTextField)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(searchEmpIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empSearchButton))
                .addGap(64, 64, 64)
                .addComponent(empSearchResultsTextField)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameTextField)
                    .addComponent(resultsEmpNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empDOBTextField)
                    .addComponent(resultsEmpDOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empAddressTextField)
                    .addComponent(resultsEmpAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPhoneTextField)
                    .addComponent(resultsEmpPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPhoneExtensionTextField)
                    .addComponent(resultsEmpPhoneExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empUsernameTextField)
                    .addComponent(resultsEmpUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empGenderTextField)
                    .addComponent(resultsEmpGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateEmployeeButton)
                    .addComponent(saveEmployeeUpdateButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search/Update Employees", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Search");

        cuNameTextField.setText("Name:");

        cuDOBTextField.setText("Date of Birth:");

        cuAddressTextField.setText("Address:");

        cuPhoneTextField.setText("Phone Number:");

        cuLicenseNumberTextField.setText("License Number:");

        cuLicenseExpiryTextField.setText("License Expiry:");

        cuAgeTextField.setText("Age:");

        resultsCuGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        resultsCuGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsCuGenderComboBoxActionPerformed(evt);
            }
        });

        resultsCuLicenseExpiryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsCuLicenseExpiryTextFieldActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setText("Search/Update Customer");

        jLabel24.setText("Search by ID:");

        searchCuIDButton.setText("Search");
        searchCuIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCuIDButtonActionPerformed(evt);
            }
        });

        cuSearchResultsTextField.setForeground(new java.awt.Color(255, 0, 51));
        cuSearchResultsTextField.setText("Search Results");

        resultsCuAgeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsCuAgeTextFieldActionPerformed(evt);
            }
        });

        cuGenderTextField.setText("Gender:");

        updateCustomerButton.setText("Update");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonActionPerformed(evt);
            }
        });

        saveCustomerUpdateButton.setText("Save");
        saveCustomerUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(cuSearchResultsTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(SearchCuIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchCuIDButton)))
                        .addGap(397, 397, 397)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(cuDOBTextField)
                                            .addGap(65, 65, 65))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cuNameTextField)
                                                .addComponent(cuLicenseNumberTextField))
                                            .addGap(51, 51, 51)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(resultsCuNameTextField))
                                        .addComponent(resultsCuDOBTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(resultsCuLicenseNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cuLicenseExpiryTextField)
                                        .addComponent(cuAgeTextField)
                                        .addComponent(cuGenderTextField))
                                    .addGap(58, 58, 58)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(updateCustomerButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(saveCustomerUpdateButton))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(resultsCuGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(resultsCuAgeTextField)
                                        .addComponent(resultsCuLicenseExpiryTextField)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cuPhoneTextField)
                                        .addComponent(cuAddressTextField))
                                    .addGap(56, 56, 56)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(resultsCuAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(resultsCuPhoneTextField))))
                            .addComponent(jLabel23))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel24)
                    .addComponent(SearchCuIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCuIDButton))
                .addGap(18, 18, 18)
                .addComponent(cuSearchResultsTextField)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuNameTextField)
                    .addComponent(resultsCuNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuDOBTextField)
                    .addComponent(resultsCuDOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuPhoneTextField)
                    .addComponent(resultsCuPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuAddressTextField)
                    .addComponent(resultsCuAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuLicenseNumberTextField)
                    .addComponent(resultsCuLicenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultsCuLicenseExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuLicenseExpiryTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuAgeTextField)
                    .addComponent(resultsCuAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultsCuGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuGenderTextField))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCustomerButton)
                    .addComponent(saveCustomerUpdateButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search/Update Customers", jPanel1);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel35.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 0, 255));
        jLabel35.setText("Add New Employee ");

        jLabel36.setText("Enter ID:");

        jLabel37.setText("Enter Name:");

        jLabel38.setText("Enter Address:");

        jLabel39.setText("Enter Phone:");

        jLabel40.setText("Enter Phone Extension:");

        jLabel41.setText("Enter Username:");

        jLabel42.setText("Select Gender:");

        jLabel43.setText("Select Date of Birth");

        addEmGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        addEmGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmGenderComboBoxActionPerformed(evt);
            }
        });

        addNewEmButton.setBackground(new java.awt.Color(204, 204, 204));
        addNewEmButton.setForeground(new java.awt.Color(255, 51, 255));
        addNewEmButton.setText("Add New Employee");
        addNewEmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(addNewEmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addEmNameTextField)
                                    .addComponent(addEmIDTextField)
                                    .addComponent(addEmAddressTextField)
                                    .addComponent(addEmPhoneTextField)
                                    .addComponent(addEmPhoneExtensionTextField)
                                    .addComponent(addEmUsernameTextField)
                                    .addComponent(addEmGenderComboBox, 0, 190, Short.MAX_VALUE)
                                    .addComponent(addEmDOBDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(addEmIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(addEmNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(addEmAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(addEmPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(addEmPhoneExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(addEmUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(addEmGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(addEmDOBDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(addNewEmButton)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Employee", jPanel4);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel26.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 255));
        jLabel26.setText("Add New Customer");

        jLabel27.setText("Enter ID:");

        jLabel28.setText("Enter Name:");

        jLabel29.setText("Enter Address:");

        jLabel30.setText("Enter Phone:");

        jLabel31.setText("Enter License Number:");

        jLabel32.setText("Select Gender:");

        jLabel33.setText("Select Date of Birth:");

        jLabel34.setText("Select License Expiry:");

        addCuGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        addCuLicenseExpiryDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCuLicenseExpiryDatePickerActionPerformed(evt);
            }
        });

        jLabel44.setText("Enter Age:");

        addCuAgeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCuAgeTextFieldActionPerformed(evt);
            }
        });

        addNewCuButton.setText("Add New Customer");
        addNewCuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel44))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addNewCuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCuNameTextField)
                            .addComponent(addCuIDTextField)
                            .addComponent(addCuAddressTextField)
                            .addComponent(addCuPhoneTextField)
                            .addComponent(addCuLicenseNumberTextField)
                            .addComponent(addCuGenderComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCuDOBDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCuLicenseExpiryDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(addCuAgeTextField))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(addCuIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(addCuNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(addCuPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(addCuAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(addCuLicenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(addCuAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(addCuDOBDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(addCuLicenseExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCuGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(29, 29, 29)
                .addComponent(addNewCuButton)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Customer", jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setText("Start Date:");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setText("Dates to view rentals between:");

        jLabel4.setText("End Date:");

        inputEndRentalDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEndRentalDateActionPerformed(evt);
            }
        });

        rentalDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Phone", "Gender", "Date Rented", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rentalDisplayTable);

        searchRentalButton.setText("Search");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputStartRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputEndRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(searchRentalButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputStartRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputEndRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(searchRentalButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTabbedPane2)
                        .addComponent(jTabbedPane1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(394, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCuLicenseExpiryDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCuLicenseExpiryDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCuLicenseExpiryDatePickerActionPerformed

    private void addEmGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmGenderComboBoxActionPerformed

    private void addCuAgeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCuAgeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCuAgeTextFieldActionPerformed

    private void resultsCuLicenseExpiryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsCuLicenseExpiryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultsCuLicenseExpiryTextFieldActionPerformed

    private void resultsCuAgeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsCuAgeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultsCuAgeTextFieldActionPerformed

    private void resultsCuGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsCuGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultsCuGenderComboBoxActionPerformed
    private void isCustomerVisible(boolean option)
    {
        cuNameTextField.setVisible(option); cuDOBTextField.setVisible(option);
        cuAddressTextField.setVisible(option); cuPhoneTextField.setVisible(option);
        cuLicenseNumberTextField.setVisible(option); cuLicenseExpiryTextField.setVisible(option);
        cuAgeTextField.setVisible(option); cuGenderTextField.setVisible(option);
        resultsCuNameTextField.setVisible(option); resultsCuDOBTextField.setVisible(option);
        resultsCuAddressTextField.setVisible(option); resultsCuPhoneTextField.setVisible(option);
        resultsCuLicenseNumberTextField.setVisible(option);resultsCuLicenseExpiryTextField.setVisible(option);
        resultsCuAgeTextField.setVisible(option);resultsCuGenderComboBox.setVisible(option);
        cuSearchResultsTextField.setVisible(option); updateCustomerButton.setVisible(option);
        saveCustomerUpdateButton.setVisible(option);
        
    }
    private void isEmployeeVisible(boolean option)
    {
        empSearchResultsTextField.setVisible(option); resultsEmpNameTextField.setVisible(option);
        resultsEmpDOBTextField.setVisible(option); resultsEmpAddressTextField.setVisible(option);
        resultsEmpPhoneTextField.setVisible(option); resultsEmpPhoneExtensionTextField.setVisible(option);
        resultsEmpUsernameTextField.setVisible(option); resultsEmpGenderComboBox.setVisible(option);
        empNameTextField.setVisible(option);empDOBTextField.setVisible(option);
        empAddressTextField.setVisible(option); empPhoneTextField.setVisible(option);
        empPhoneExtensionTextField.setVisible(option); empUsernameTextField.setVisible(option);
        empGenderTextField.setVisible(option); updateEmployeeButton.setVisible(option);
        
        
    }
    
    private void isEmployeeSaveVisible(boolean option)
    {
        saveEmployeeUpdateButton.setVisible(option);
    }
    
    private void isCustomerSaveVisible(boolean option)
    {
        saveCustomerUpdateButton.setVisible(option);
    }
    
    private void isEmployeeEditable(boolean option)
    {
        resultsEmpNameTextField.setEditable(option);
        resultsEmpDOBTextField.setEditable(option);
        resultsEmpAddressTextField.setEditable(option);
        resultsEmpPhoneTextField.setEditable(option);
        resultsEmpPhoneExtensionTextField.setEditable(option);
        resultsEmpUsernameTextField.setEditable(option);
        resultsEmpGenderComboBox.setEditable(option);
    }
    
    private void isCustomerEditable(boolean option)
    {
        resultsCuNameTextField.setEditable(option);
        resultsCuDOBTextField.setEditable(option);
        resultsCuAddressTextField.setEditable(option);
        resultsCuPhoneTextField.setEditable(option);
        resultsCuLicenseNumberTextField.setEditable(option);
        resultsCuLicenseExpiryTextField.setEditable(option);
        resultsCuAgeTextField.setEditable(option);
        resultsCuGenderComboBox.setEditable(option);
    }
    private void addNewEmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEmButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(addEmIDTextField.getText());
        String name = addEmNameTextField.getText();
        String address = addEmAddressTextField.getText();
        String phone = addEmPhoneTextField.getText();
        String phoneExtension = addEmPhoneExtensionTextField.getText();
        String userName = addEmUsernameTextField.getText();
        char gender = addEmGenderComboBox.getSelectedItem().toString().charAt(0);
        Date dateOfBirth = addEmDOBDatePicker.getDate();
        Employee em = new Employee(userName, phoneExtension, id, name, dateOfBirth, address, phone, gender);
        employees.add(em);
        JOptionPane.showMessageDialog(this, "Employee Added Successfully");
        addEmIDTextField.setText(""); addEmNameTextField.setText(""); addEmAddressTextField.setText(""); addEmPhoneTextField.setText("");
        addEmPhoneExtensionTextField.setText(""); addEmUsernameTextField.setText("");
    }//GEN-LAST:event_addNewEmButtonActionPerformed

    private void addNewCuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCuButtonActionPerformed
        int id = Integer.parseInt(addCuIDTextField.getText());
        String name = addCuNameTextField.getText();
        String address = addCuAddressTextField.getText();
        String phone = addCuPhoneTextField.getText();
        String licenseNumber = addCuLicenseNumberTextField.getText();
        char gender = addCuGenderComboBox.getSelectedItem().toString().charAt(0);
        Date dateOfBirth = addCuDOBDatePicker.getDate();
        Date licenseExpiry = addCuLicenseExpiryDatePicker.getDate();
        int age = Integer.parseInt(addCuAgeTextField.getText());
        Customer cu = new Customer(age, licenseNumber, licenseExpiry, id, name, dateOfBirth, address, phone, gender);
        customers.add(cu);
        JOptionPane.showMessageDialog(this, "Customer Added Successfully");
        addCuIDTextField.setText(""); addCuNameTextField.setText(""); addCuAddressTextField.setText("");
        addCuPhoneTextField.setText(""); addCuLicenseNumberTextField.setText(""); addCuAgeTextField.setText("");
    }//GEN-LAST:event_addNewCuButtonActionPerformed

    private void searchCuIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCuIDButtonActionPerformed
        int id = Integer.parseInt(SearchCuIDTextField.getText());
        Customer found = null;
        for (Customer cu : customers)
        {
            if(cu.getPersonID() == id)
            {
                found = cu;
                isCustomerVisible(true);
                break;
            }
        }
        if(found == null)
        {
            JOptionPane.showMessageDialog(this, "No Customer found with this ID");
        }else
        {
            resultsCuNameTextField.setText(found.getName());
            resultsCuAddressTextField.setText(found.getName());
            resultsCuPhoneTextField.setText(found.getPhone());
            resultsCuLicenseNumberTextField.setText(found.getPhone());
            resultsCuGenderComboBox.getModel().setSelectedItem(found.getGender());        
            //resultsCuGenderComboBox.setSelectedItem(found.getGender()); 
            resultsCuDOBTextField.setText(found.getDateOfBirth().toString());
            resultsCuLicenseExpiryTextField.setText(found.getLicenseExpiry().toString());
            resultsCuAgeTextField.setText(String.valueOf(found.getAge()));
            isCustomerVisible(true);
            isCustomerEditable(false);
            
        }
    }//GEN-LAST:event_searchCuIDButtonActionPerformed

    private void empSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSearchButtonActionPerformed
        int id = Integer.parseInt(searchEmpIDTextField.getText());
            Employee found = null;
            for (Employee em : employees)
            {
                if(em.getPersonID() == id)
                {
                    found = em;
                    isEmployeeVisible(true);
                    break;
                }
            }
        if(found == null)
        {
            JOptionPane.showMessageDialog(this, "No Employee found with this ID");           
        }
        else
        {
            resultsEmpNameTextField.setText(found.getName());
            resultsEmpDOBTextField.setText(found.getDateOfBirth().toString());
            resultsEmpAddressTextField.setText(found.getAddress());
            resultsEmpPhoneTextField.setText(found.getPhone());
            resultsEmpPhoneExtensionTextField.setText(found.getPhoneExtension());
            resultsEmpUsernameTextField.setText(found.getUserName());
            resultsEmpGenderComboBox.getModel().setSelectedItem(found.getGender());
        }
        isEmployeeVisible(true);
        isEmployeeEditable(false);
        isEmployeeSaveVisible(false);
    }//GEN-LAST:event_empSearchButtonActionPerformed

    Employee searchAEmployee(int id)
    {
        Employee found = null;
        for (Employee em : employees)
        {
            if(em.getPersonID() == id)
            {
                found = em;
                break;
            }
        }
        return found;
        
    }

    
    Customer searchACustomer(int id)
    {
        Customer found = null;
        for (Customer cu : customers)
        {
            if(cu.getPersonID() == id)
            {
                found = cu;
                break;
            }
        }
        return found;
    
    }

    
    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed

        
        int id = Integer.parseInt(searchEmpIDTextField.getText());     
        Employee em = searchAEmployee(id);
        if(em==null)
        {
            JOptionPane.showMessageDialog(this, "Sorry Employee not found with entered ID");
        }else
        {
            isEmployeeVisible(true);
            isEmployeeEditable(true);

        JOptionPane.showMessageDialog(this, "Enter new Employee details");    
            
        }
        isEmployeeSaveVisible(true);
        
        

        
        
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void updateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonActionPerformed
        int id = Integer.parseInt(SearchCuIDTextField.getText());     
        Customer cu = searchACustomer(id);
        if(cu==null)
        {
            JOptionPane.showMessageDialog(this, "Sorry Customer not found with entered ID");
        }else
        {
            isCustomerVisible(true);
            isCustomerEditable(true);

        JOptionPane.showMessageDialog(this, "Enter new Customer details");    

       

        }
        isCustomerSaveVisible(true);
    }//GEN-LAST:event_updateCustomerButtonActionPerformed

    private void saveCustomerUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerUpdateButtonActionPerformed
        int id = Integer.parseInt(SearchCuIDTextField.getText());
        String newCustomerName = resultsCuNameTextField.getText();
        String newCustomerDateOfBirth = resultsCuDOBTextField.getText();
        String newCustomerAddress = resultsCuAddressTextField.getText();
        String newCustomerPhone = resultsCuPhoneTextField.getText();
        String newCustomerLicenseNumber = resultsCuLicenseNumberTextField.getText();
        String newCustomerLicenseExpiry = resultsCuLicenseExpiryTextField.getText();
        int newCustomerAge = Integer.parseInt(resultsCuAgeTextField.getText());
        char newCustomerGender = resultsCuGenderComboBox.getSelectedItem().toString().charAt(0);
        Customer cu = searchACustomer(id);
        cu.setAddress(newCustomerAddress);
        cu.setName(newCustomerName);
        cu.setGender(newCustomerGender);        
        cu.setLicenseNumber(newCustomerLicenseNumber);
        cu.setPhone(newCustomerPhone);
        cu.setName(newCustomerName);
        
        
        
        
        JOptionPane.showMessageDialog(this, "Customer information updated.");
        isCustomerVisible(false);
        isCustomerSaveVisible(false);
        SearchCuIDTextField.setText("");
    }//GEN-LAST:event_saveCustomerUpdateButtonActionPerformed

    private void saveEmployeeUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEmployeeUpdateButtonActionPerformed
        int id = Integer.parseInt(searchEmpIDTextField.getText());
        String newEmployeeName = resultsEmpNameTextField.getText();
        String newEmployeeDateOfBirth = resultsEmpDOBTextField.getText();
        String newEmployeeAddress = resultsEmpAddressTextField.getText();
        String newEmployeePhone = resultsEmpPhoneTextField.getText();        
        char newEmployeeGender = resultsEmpGenderComboBox.getSelectedItem().toString().charAt(0);
        Employee em = searchAEmployee(id);
        em.setAddress(newEmployeeAddress);
        em.setName(newEmployeeName);
        em.setGender(newEmployeeGender);        
        em.setPhone(newEmployeePhone);
        em.setName(newEmployeeName);
        
        
        
        
        JOptionPane.showMessageDialog(this, "Customer information updated.");
        isEmployeeVisible(false);
        isEmployeeSaveVisible(false);
        searchEmpIDTextField.setText("");
    }//GEN-LAST:event_saveEmployeeUpdateButtonActionPerformed

    private void inputEndRentalDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEndRentalDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEndRentalDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAndCustomerManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAndCustomerManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAndCustomerManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAndCustomerManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAndCustomerManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchCuIDTextField;
    private javax.swing.JTextField addCuAddressTextField;
    private javax.swing.JTextField addCuAgeTextField;
    private org.jdesktop.swingx.JXDatePicker addCuDOBDatePicker;
    private javax.swing.JComboBox<String> addCuGenderComboBox;
    private javax.swing.JTextField addCuIDTextField;
    private org.jdesktop.swingx.JXDatePicker addCuLicenseExpiryDatePicker;
    private javax.swing.JTextField addCuLicenseNumberTextField;
    private javax.swing.JTextField addCuNameTextField;
    private javax.swing.JTextField addCuPhoneTextField;
    private javax.swing.JTextField addEmAddressTextField;
    private org.jdesktop.swingx.JXDatePicker addEmDOBDatePicker;
    private javax.swing.JComboBox<String> addEmGenderComboBox;
    private javax.swing.JTextField addEmIDTextField;
    private javax.swing.JTextField addEmNameTextField;
    private javax.swing.JTextField addEmPhoneExtensionTextField;
    private javax.swing.JTextField addEmPhoneTextField;
    private javax.swing.JTextField addEmUsernameTextField;
    private javax.swing.JButton addNewCuButton;
    private javax.swing.JButton addNewEmButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cuAddressTextField;
    private javax.swing.JLabel cuAgeTextField;
    private javax.swing.JLabel cuDOBTextField;
    private javax.swing.JLabel cuGenderTextField;
    private javax.swing.JLabel cuLicenseExpiryTextField;
    private javax.swing.JLabel cuLicenseNumberTextField;
    private javax.swing.JLabel cuNameTextField;
    private javax.swing.JLabel cuPhoneTextField;
    private javax.swing.JLabel cuSearchResultsTextField;
    private javax.swing.JLabel empAddressTextField;
    private javax.swing.JLabel empDOBTextField;
    private javax.swing.JLabel empGenderTextField;
    private javax.swing.JLabel empNameTextField;
    private javax.swing.JLabel empPhoneExtensionTextField;
    private javax.swing.JLabel empPhoneTextField;
    private javax.swing.JButton empSearchButton;
    private javax.swing.JLabel empSearchResultsTextField;
    private javax.swing.JLabel empUsernameTextField;
    private javax.swing.JTextField inputEndRentalDate;
    private javax.swing.JTextField inputStartRentalDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable rentalDisplayTable;
    private javax.swing.JTextField resultsCuAddressTextField;
    private javax.swing.JTextField resultsCuAgeTextField;
    private javax.swing.JTextField resultsCuDOBTextField;
    private javax.swing.JComboBox<String> resultsCuGenderComboBox;
    private javax.swing.JTextField resultsCuLicenseExpiryTextField;
    private javax.swing.JTextField resultsCuLicenseNumberTextField;
    private javax.swing.JTextField resultsCuNameTextField;
    private javax.swing.JTextField resultsCuPhoneTextField;
    private javax.swing.JTextField resultsEmpAddressTextField;
    private javax.swing.JTextField resultsEmpDOBTextField;
    private javax.swing.JComboBox<String> resultsEmpGenderComboBox;
    private javax.swing.JTextField resultsEmpNameTextField;
    private javax.swing.JTextField resultsEmpPhoneExtensionTextField;
    private javax.swing.JTextField resultsEmpPhoneTextField;
    private javax.swing.JTextField resultsEmpUsernameTextField;
    private javax.swing.JButton saveCustomerUpdateButton;
    private javax.swing.JButton saveEmployeeUpdateButton;
    private javax.swing.JButton searchCuIDButton;
    private javax.swing.JTextField searchEmpIDTextField;
    private javax.swing.JButton searchRentalButton;
    private javax.swing.JButton updateCustomerButton;
    private javax.swing.JButton updateEmployeeButton;
    // End of variables declaration//GEN-END:variables
}
