/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TMG.Assignment2;

import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thomaskerr-smith
 */
public final class StockManagement extends javax.swing.JFrame 
{
    
    static public ArrayList<GuitarModels> guitars = new ArrayList<>();
    
    GuitarModels g1 = new GuitarModels("MuddyWood", "Acoustic", "Gibson", 
    "Sitka", "Sitka", 100, 1987, 80, "White", 98, 75, 65, "In Store", 
    LocalDate.of(2021, Month.APRIL, 14), LocalDate.of(2021, Month.APRIL, 21));
    
    GuitarModels g2 = new GuitarModels("Axe Window", "Electric", "Martin", 
    "Indian Rosewood", "Cedar", 95, 1995, 40, "White", 95, 80, 105, "In Store", 
    LocalDate.of(2021, Month.APRIL, 18), LocalDate.of(2021, Month.APRIL, 25));
    
    /**
     * Creates new form StockManagement
     * @param option
     */

    public void isGuitarModelsEditable(boolean option)
    {
        RentTextFieldSearch.setEditable(option);
        StatusComboBox.setEditable(option);
        //DayRentedTextFieldSearch.setEditable(option);
        //DayDueTextFieldSearch.setEditable(option);
    }
    
    
    public void isVisible(boolean option)
   {
           SerialNumberTextFieldSearch.setVisible(option);
           ManufactureTextFieldSearch.setVisible(option);
           RentTextFieldSearch.setVisible(option);
           ColourTextFieldSearch.setVisible(option);
           LengthtextFieldSearch.setVisible(option);
           WidthTextFieldSearch.setVisible(option);
           HeightTextFieldSearch.setVisible(option);
           ModelTextFieldSearch.setVisible(option);
           BuilderTextFieldSearch.setVisible(option);
           TypeTextFieldSearch.setVisible(option);
           BackWoodTextFieldSearch.setVisible(option);
           TopWoodTextFieldSearch.setVisible(option);
   }
    
    
    public StockManagement() {
        initComponents();
        isVisible();
    
        guitars.add(g1);
        guitars.add(g2);
        
        DefaultTableModel model = (DefaultTableModel) DisplayTable.getModel();
        model.setRowCount(0);
        Object rows[] = new Object[5];
        
        for(int i = 0; i < guitars.size(); i++)
        {
            rows[0] = guitars.get(i).guitarSerialNumber;
            rows[1] = guitars.get(i).guitarModel;
            rows[2] = guitars.get(i).guitarStatus;
            rows[3] = guitars.get(i).guitarRentCharge;
            rows[4] = guitars.get(i).getGuitarYear();
            model.addRow(rows);
        }
         
    }

    public ArrayList<GuitarModels> getGuitars()
    {
        return guitars;
    }

    /**
     *
     * @param guitars
     */
    public void Guitars(ArrayList<GuitarModels> guitars)
    {
        StockManagement.guitars = guitars;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AddGuitarPane = new javax.swing.JPanel();
        SerialLabel = new javax.swing.JLabel();
        ManufactureLabel = new javax.swing.JLabel();
        RentLabel = new javax.swing.JLabel();
        ColourLabel = new javax.swing.JLabel();
        LengthLabel = new javax.swing.JLabel();
        WidthLabel = new javax.swing.JLabel();
        HeightLabel = new javax.swing.JLabel();
        ModelLabel = new javax.swing.JLabel();
        BuilderLabel = new javax.swing.JLabel();
        TypeLabel = new javax.swing.JLabel();
        BackWoodLabel = new javax.swing.JLabel();
        TopWoodLabel = new javax.swing.JLabel();
        SerialNumberTextField = new javax.swing.JTextField();
        RentPerDayTextfield = new javax.swing.JTextField();
        GuitarColourTextField = new javax.swing.JTextField();
        ManufactureTextField = new javax.swing.JTextField();
        GuitarLengthTextField = new javax.swing.JTextField();
        GuitarWidthTextField = new javax.swing.JTextField();
        GuitarHeightTextField = new javax.swing.JTextField();
        GuitarModelTextField = new javax.swing.JTextField();
        BuilderComboBox = new javax.swing.JComboBox<>();
        TypeComboBox = new javax.swing.JComboBox<>();
        BackWoodComboBox = new javax.swing.JComboBox<>();
        TopWoodComboBox = new javax.swing.JComboBox<>();
        AddGuitarButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        SearchItemPane = new javax.swing.JPanel();
        SearchItemButton = new javax.swing.JButton();
        searchSerialTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SerialNumberTextFieldSearch = new javax.swing.JTextField();
        ManufactureTextFieldSearch = new javax.swing.JTextField();
        RentTextFieldSearch = new javax.swing.JTextField();
        ColourTextFieldSearch = new javax.swing.JTextField();
        LengthtextFieldSearch = new javax.swing.JTextField();
        WidthTextFieldSearch = new javax.swing.JTextField();
        HeightTextFieldSearch = new javax.swing.JTextField();
        ModelTextFieldSearch = new javax.swing.JTextField();
        BuilderTextFieldSearch = new javax.swing.JTextField();
        TypeTextFieldSearch = new javax.swing.JTextField();
        BackWoodTextFieldSearch = new javax.swing.JTextField();
        TopWoodTextFieldSearch = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DayRentedTextFieldSearch = new javax.swing.JTextField();
        DayDueTextFieldSearch = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        SaveUpdateButton = new javax.swing.JButton();
        StatusTextFieldSearch = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllGuitarsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        AddGuitarPane.setBackground(new java.awt.Color(204, 204, 204));

        SerialLabel.setText("Serial Number: ");

        ManufactureLabel.setText("Year Of Manufacture: ");

        RentLabel.setText("Rent Per Day: ");

        ColourLabel.setText("Guitar Colour: ");

        LengthLabel.setText("Guitar Length");

        WidthLabel.setText("Guitar Width: ");

        HeightLabel.setText("Guitar Height:");

        ModelLabel.setText("Guitar Model: ");

        BuilderLabel.setText("Guitar Builder:");

        TypeLabel.setText("Guitar Type: ");

        BackWoodLabel.setText("Guitar Back wood: ");

        TopWoodLabel.setText("Guitar Top Wood:");

        SerialNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialNumberTextFieldActionPerformed(evt);
            }
        });

        RentPerDayTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentPerDayTextfieldActionPerformed(evt);
            }
        });

        GuitarColourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuitarColourTextFieldActionPerformed(evt);
            }
        });

        ManufactureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufactureTextFieldActionPerformed(evt);
            }
        });

        GuitarLengthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuitarLengthTextFieldActionPerformed(evt);
            }
        });

        GuitarWidthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuitarWidthTextFieldActionPerformed(evt);
            }
        });

        GuitarHeightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuitarHeightTextFieldActionPerformed(evt);
            }
        });

        GuitarModelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuitarModelTextFieldActionPerformed(evt);
            }
        });

        BuilderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fender", "Martin", "Gibson", "Collings", "Olson", "Ryan", "Paras", "Raj" }));

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acoustic", "Electric", " " }));

        BackWoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian Rosewood", "Brazilian Rosewood", "Mahogany", "Maple", "Cocobolo", "Cedar", "Adirondack", "Alder", "Sitka" }));

        TopWoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian Rosewood", "Brazilian Rosewood", "Mahogany", "Maple", "Cocobolo", "Cedar", "Adirondack", "Alder", "Sitka" }));

        AddGuitarButton.setText("ADD");
        AddGuitarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGuitarButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Guitar Status:");

        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Store", "Rented Out", "Under Maintenance" }));

        javax.swing.GroupLayout AddGuitarPaneLayout = new javax.swing.GroupLayout(AddGuitarPane);
        AddGuitarPane.setLayout(AddGuitarPaneLayout);
        AddGuitarPaneLayout.setHorizontalGroup(
            AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGuitarPaneLayout.createSequentialGroup()
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddGuitarPaneLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RentLabel)
                            .addComponent(SerialLabel)
                            .addComponent(ManufactureLabel)
                            .addGroup(AddGuitarPaneLayout.createSequentialGroup()
                                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ColourLabel)
                                    .addComponent(LengthLabel)
                                    .addComponent(WidthLabel)
                                    .addComponent(HeightLabel)
                                    .addComponent(ModelLabel)
                                    .addComponent(BuilderLabel)
                                    .addComponent(TypeLabel)
                                    .addComponent(BackWoodLabel)
                                    .addComponent(TopWoodLabel)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BackWoodComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SerialNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GuitarModelTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GuitarHeightTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GuitarWidthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GuitarLengthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RentPerDayTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GuitarColourTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuilderComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ManufactureTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(TopWoodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(StatusComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(AddGuitarPaneLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(AddGuitarButton)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        AddGuitarPaneLayout.setVerticalGroup(
            AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGuitarPaneLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SerialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SerialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManufactureLabel)
                    .addComponent(ManufactureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RentLabel)
                    .addComponent(RentPerDayTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColourLabel)
                    .addComponent(GuitarColourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LengthLabel)
                    .addComponent(GuitarLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WidthLabel)
                    .addComponent(GuitarWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeightLabel)
                    .addComponent(GuitarHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModelLabel)
                    .addComponent(GuitarModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuilderLabel)
                    .addComponent(BuilderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLabel)
                    .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackWoodLabel)
                    .addComponent(BackWoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TopWoodLabel)
                    .addComponent(TopWoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddGuitarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(AddGuitarButton)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Guitar", AddGuitarPane);

        SearchItemPane.setBackground(new java.awt.Color(204, 204, 204));

        SearchItemButton.setText("Search Item");
        SearchItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchItemButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Search item by serial");

        jLabel2.setText("Serial Number");

        jLabel3.setText("Year Of Manufacture");

        jLabel4.setText("Rent Per Day");

        jLabel5.setText("Guitar Colour");

        jLabel6.setText("Guitar Length");

        jLabel7.setText("Guitar Width");

        jLabel8.setText("Guitar Height");

        jLabel9.setText("Guitar Model");

        jLabel10.setText("Guitar Builder");

        jLabel11.setText("Guitar Type");

        jLabel12.setText("Guitar Back wood");

        jLabel13.setText("Guitar Top Wood");

        SerialNumberTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialNumberTextFieldSearchActionPerformed(evt);
            }
        });

        ManufactureTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufactureTextFieldSearchActionPerformed(evt);
            }
        });

        RentTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentTextFieldSearchActionPerformed(evt);
            }
        });

        ColourTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColourTextFieldSearchActionPerformed(evt);
            }
        });

        LengthtextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LengthtextFieldSearchActionPerformed(evt);
            }
        });

        WidthTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WidthTextFieldSearchActionPerformed(evt);
            }
        });

        HeightTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightTextFieldSearchActionPerformed(evt);
            }
        });

        ModelTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelTextFieldSearchActionPerformed(evt);
            }
        });

        BuilderTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuilderTextFieldSearchActionPerformed(evt);
            }
        });

        TypeTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeTextFieldSearchActionPerformed(evt);
            }
        });

        BackWoodTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackWoodTextFieldSearchActionPerformed(evt);
            }
        });

        TopWoodTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopWoodTextFieldSearchActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update Guitar Information");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Day Rented");

        jLabel15.setText("Day Due Back");

        DayRentedTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayRentedTextFieldSearchActionPerformed(evt);
            }
        });

        DayDueTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayDueTextFieldSearchActionPerformed(evt);
            }
        });

        jLabel16.setText("Guitar Status");

        SaveUpdateButton.setText("Save Guitar Information");
        SaveUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveUpdateButtonActionPerformed(evt);
            }
        });

        StatusTextFieldSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN_STORE", "RENTED_OUT", "UNDER_MAINTENANCE" }));

        javax.swing.GroupLayout SearchItemPaneLayout = new javax.swing.GroupLayout(SearchItemPane);
        SearchItemPane.setLayout(SearchItemPaneLayout);
        SearchItemPaneLayout.setHorizontalGroup(
            SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchItemPaneLayout.createSequentialGroup()
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchItemPaneLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(SearchItemPaneLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveUpdateButton))
                    .addGroup(SearchItemPaneLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(searchSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(SearchItemButton))
                    .addGroup(SearchItemPaneLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addGroup(SearchItemPaneLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel16)))
                        .addGap(34, 34, 34)
                        .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SerialNumberTextFieldSearch)
                            .addComponent(ManufactureTextFieldSearch)
                            .addComponent(RentTextFieldSearch)
                            .addComponent(ColourTextFieldSearch)
                            .addComponent(LengthtextFieldSearch)
                            .addComponent(WidthTextFieldSearch)
                            .addComponent(HeightTextFieldSearch)
                            .addComponent(ModelTextFieldSearch)
                            .addComponent(BuilderTextFieldSearch)
                            .addComponent(TypeTextFieldSearch)
                            .addComponent(BackWoodTextFieldSearch)
                            .addComponent(TopWoodTextFieldSearch)
                            .addComponent(DayRentedTextFieldSearch)
                            .addComponent(DayDueTextFieldSearch)
                            .addComponent(StatusTextFieldSearch, 0, 276, Short.MAX_VALUE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        SearchItemPaneLayout.setVerticalGroup(
            SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchItemPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchItemButton)
                    .addComponent(searchSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SerialNumberTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ManufactureTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(StatusTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RentTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ColourTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LengthtextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(WidthTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(HeightTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ModelTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(BuilderTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TypeTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(BackWoodTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TopWoodTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayRentedTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(DayDueTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchItemPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(SaveUpdateButton))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Item", SearchItemPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Serial number", "Guitar Model", "Guitar Status", "Rent Charge", "Year"
            }
        ));
        jScrollPane2.setViewportView(DisplayTable);

        jTabbedPane5.addTab("Available Guitars", jScrollPane2);

        AllGuitarsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Serial Number", "Guitar Model", "Guitar Status", "Rent Charge", "Year"
            }
        ));
        jScrollPane1.setViewportView(AllGuitarsTable);

        jTabbedPane6.addTab("", jScrollPane1);

        jTabbedPane5.addTab("All Guitars", jTabbedPane6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SerialNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SerialNumberTextFieldActionPerformed

    private void RentPerDayTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentPerDayTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentPerDayTextfieldActionPerformed

    private void GuitarColourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuitarColourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuitarColourTextFieldActionPerformed

    private void ManufactureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufactureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManufactureTextFieldActionPerformed

    private void GuitarLengthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuitarLengthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuitarLengthTextFieldActionPerformed

    private void GuitarWidthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuitarWidthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuitarWidthTextFieldActionPerformed

    private void GuitarHeightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuitarHeightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuitarHeightTextFieldActionPerformed

    private void GuitarModelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuitarModelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuitarModelTextFieldActionPerformed

    private void AddGuitarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGuitarButtonActionPerformed
        // TODO add your handling code here:
        double guitarSerialNumber = Double.parseDouble(SerialNumberTextField.getText());
        String guitarColour = GuitarColourTextField.getText();
        double guitarRentCharge = Double.parseDouble(RentPerDayTextfield.getText());
        String guitarModel = GuitarModelTextField.getText();
        int guitarYear = Integer.parseInt(ManufactureTextField.getText());
        double guitarLength = Double.parseDouble(GuitarLengthTextField.getText());
        double guitarWidth = Double.parseDouble(GuitarWidthTextField.getText());
        double guitarHeight = Double.parseDouble(GuitarHeightTextField.getText());
        String guitarBuilder = (String) BuilderComboBox.getSelectedItem();
        String guitarType = (String) TypeComboBox.getSelectedItem();
        String guitarBackWood = (String) BackWoodComboBox.getSelectedItem();
        String guitarTopWood = (String) TopWoodComboBox.getSelectedItem();
        String guitarStatus = (String) StatusComboBox.getSelectedItem();
        
        GuitarModels newGuitar = new GuitarModels(guitarModel, guitarType, guitarBuilder, 
        guitarBackWood, guitarTopWood, guitarSerialNumber, guitarYear, guitarRentCharge, 
        guitarColour, guitarLength, guitarWidth, guitarHeight, guitarStatus, LocalDate.MIN, LocalDate.MIN);
        
        guitars.add(newGuitar);
        
        DefaultTableModel model = (DefaultTableModel) AllGuitarsTable.getModel();
        model.setRowCount(0);
        Object rows[] = new Object[5];
        
        for(int i = 0; i < guitars.size(); i++)
        {
            rows[0] = guitars.get(i).guitarSerialNumber;
            rows[1] = guitars.get(i).guitarModel;
            rows[2] = guitars.get(i).guitarStatus;
            rows[3] = guitars.get(i).guitarRentCharge;
            rows[4] = guitars.get(i).getGuitarYear();
            model.addRow(rows);
        }
        
        JOptionPane.showMessageDialog(this, "Guitar Added succesfully"); 
        
    }//GEN-LAST:event_AddGuitarButtonActionPerformed

        
        GuitarModels searchGuitar(int guitarSerialNumber)
     {
         GuitarModels found = null;
         for(GuitarModels g : guitars)
         {
             if(g.getGuitarSerialNumber()==guitarSerialNumber)
             {
                 found = g;
                 break;
             }
         }
        return found;
        
     }
    
    private void SearchItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchItemButtonActionPerformed
        // TODO add your handling code here:
   
       double guitarSerialNumber = Double.parseDouble(searchSerialTextField.getText());
       GuitarModels g = searchGuitar((int) guitarSerialNumber);
       if(g==null)
       {
    JOptionPane.showMessageDialog(this, "Sorry no guitar with this serial number");
       }else
       {
           isVisible(true);
           isGuitarModelsEditable(false);
           
           SerialNumberTextFieldSearch.setText(g.getGuitarSerialNumber()+"");
           ManufactureTextFieldSearch.setText(g.getGuitarYear()+"");
           RentTextFieldSearch.setText(g.getGuitarRentCharge()+"");
           ColourTextFieldSearch.setText(g.getGuitarColour()+"");
           LengthtextFieldSearch.setText(g.getGuitarLength()+"");
           WidthTextFieldSearch.setText(g.getGuitarWidth()+"");
           HeightTextFieldSearch.setText(g.getGuitarHeight()+"");
           ModelTextFieldSearch.setText(g.getGuitarModel()+"");
           BuilderTextFieldSearch.setText(g.getGuitarBuilder()+"");
           TypeTextFieldSearch.setText(g.getGuitarType()+"");
           BackWoodTextFieldSearch.setText(g.getGuitarBackWood()+"");
           TopWoodTextFieldSearch.setText(g.getGuitarTopWood()+"");
           DayRentedTextFieldSearch.setText(g.getDayRented()+"");
           DayDueTextFieldSearch.setText(g.getDayReturn()+"");
           StatusTextFieldSearch.setSelectedItem(g.getGuitarStatus()+"");
           
           
       }
        isVisible(true);
  
    }//GEN-LAST:event_SearchItemButtonActionPerformed

    private void SerialNumberTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialNumberTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SerialNumberTextFieldSearchActionPerformed

    private void ManufactureTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufactureTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManufactureTextFieldSearchActionPerformed

    private void RentTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentTextFieldSearchActionPerformed

    private void ColourTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColourTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColourTextFieldSearchActionPerformed

    private void LengthtextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LengthtextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LengthtextFieldSearchActionPerformed

    private void WidthTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WidthTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WidthTextFieldSearchActionPerformed

    private void HeightTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightTextFieldSearchActionPerformed

    private void ModelTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelTextFieldSearchActionPerformed

    private void BuilderTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuilderTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuilderTextFieldSearchActionPerformed

    private void TypeTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeTextFieldSearchActionPerformed

    private void BackWoodTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackWoodTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackWoodTextFieldSearchActionPerformed

    private void TopWoodTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopWoodTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TopWoodTextFieldSearchActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        
        double guitarSerialNumber = Double.parseDouble(searchSerialTextField.getText());
        GuitarModels g = searchGuitar((int) guitarSerialNumber);
        if(g==null)
        {
            JOptionPane.showMessageDialog(this, "Sorry this serial number does not much a guitar");
        }else
        {
            isGuitarModelsEditable(true);
            
            RentTextFieldSearch.setText("");
            //StatusComboBox.setSelectedItem("");
            //DayRentedTextFieldSearch.setText("");
            //DayDueTextFieldSearch.setText("");
            
            
        
        JOptionPane.showMessageDialog(this, "Enter new Guitar Information");
            
        }
        
        
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SaveUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveUpdateButtonActionPerformed
        // TODO add your handling code here:
       isGuitarModelsEditable(true);
        
       double guitarSerialNumber = Double.parseDouble(searchSerialTextField.getText());
       GuitarModels g = searchGuitar((int) guitarSerialNumber);
       
       double guitarRentCharge = Double.parseDouble(RentTextFieldSearch.getText());
       g.setGuitarRentCharge(guitarRentCharge);
       
       String guitarStatus = (String) StatusComboBox.getSelectedItem();
       g.setGuitarStatus(guitarStatus);
       
       DefaultTableModel model = (DefaultTableModel) AllGuitarsTable.getModel();
       model.setRowCount(0);
       Object rows[] = new Object[5];
        
       for(int i = 0; i < guitars.size(); i++)
       {
            rows[0] = guitars.get(i).guitarSerialNumber;
            rows[1] = guitars.get(i).guitarModel;
            rows[2] = guitars.get(i).guitarStatus;
            rows[3] = guitars.get(i).guitarRentCharge;
            rows[4] = guitars.get(i).getGuitarYear();
            model.addRow(rows);
        
        JOptionPane.showMessageDialog(this, "Updated succesfully");    
       }
      
    }//GEN-LAST:event_SaveUpdateButtonActionPerformed

    private void DayDueTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayDueTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayDueTextFieldSearchActionPerformed

    private void DayRentedTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayRentedTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayRentedTextFieldSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManagement().setVisible(true);
            }
        });
    } 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddGuitarButton;
    private javax.swing.JPanel AddGuitarPane;
    private javax.swing.JTable AllGuitarsTable;
    private javax.swing.JComboBox<String> BackWoodComboBox;
    private javax.swing.JLabel BackWoodLabel;
    private javax.swing.JTextField BackWoodTextFieldSearch;
    private javax.swing.JComboBox<String> BuilderComboBox;
    private javax.swing.JLabel BuilderLabel;
    private javax.swing.JTextField BuilderTextFieldSearch;
    private javax.swing.JLabel ColourLabel;
    private javax.swing.JTextField ColourTextFieldSearch;
    private javax.swing.JTextField DayDueTextFieldSearch;
    private javax.swing.JTextField DayRentedTextFieldSearch;
    private javax.swing.JTable DisplayTable;
    private javax.swing.JTextField GuitarColourTextField;
    private javax.swing.JTextField GuitarHeightTextField;
    private javax.swing.JTextField GuitarLengthTextField;
    private javax.swing.JTextField GuitarModelTextField;
    private javax.swing.JTextField GuitarWidthTextField;
    private javax.swing.JLabel HeightLabel;
    private javax.swing.JTextField HeightTextFieldSearch;
    private javax.swing.JLabel LengthLabel;
    private javax.swing.JTextField LengthtextFieldSearch;
    private javax.swing.JLabel ManufactureLabel;
    private javax.swing.JTextField ManufactureTextField;
    private javax.swing.JTextField ManufactureTextFieldSearch;
    private javax.swing.JLabel ModelLabel;
    private javax.swing.JTextField ModelTextFieldSearch;
    private javax.swing.JLabel RentLabel;
    private javax.swing.JTextField RentPerDayTextfield;
    private javax.swing.JTextField RentTextFieldSearch;
    private javax.swing.JButton SaveUpdateButton;
    private javax.swing.JButton SearchItemButton;
    private javax.swing.JPanel SearchItemPane;
    private javax.swing.JLabel SerialLabel;
    private javax.swing.JTextField SerialNumberTextField;
    private javax.swing.JTextField SerialNumberTextFieldSearch;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JComboBox<String> StatusTextFieldSearch;
    private javax.swing.JComboBox<String> TopWoodComboBox;
    private javax.swing.JLabel TopWoodLabel;
    private javax.swing.JTextField TopWoodTextFieldSearch;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JTextField TypeTextFieldSearch;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel WidthLabel;
    private javax.swing.JTextField WidthTextFieldSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField searchSerialTextField;
    // End of variables declaration//GEN-END:variables
}
